
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false

      properties:
        schema.registry.url: http://localhost:8081
    listener:
      ack-mode: manual
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true