FROM quay.io/debezium/connect:latest
ARG CONFLUENT_VERSION=7.6.0
RUN pwd
WORKDIR /kafka/libs
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/7.6.0/kafka-connect-avro-converter-${CONFLUENT_VERSION}.jar
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/7.6.0/kafka-avro-serializer-${CONFLUENT_VERSION}.jar
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-data/7.6.0/kafka-connect-avro-data-${CONFLUENT_VERSION}.jar
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.6.0/kafka-schema-registry-client-${CONFLUENT_VERSION}.jar
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/7.6.0/kafka-schema-serializer-${CONFLUENT_VERSION}.jar
RUN curl -O https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/7.6.0/kafka-schema-converter-${CONFLUENT_VERSION}.jar

# apache avro
RUN curl -O https://repo.maven.apache.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar

# commons
RUN curl -O https://repo.maven.apache.org/maven2/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar

RUN curl -O https://repo.maven.apache.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
RUN curl -O https://repo.maven.apache.org/maven2/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
RUN curl -O https://repo.maven.apache.org/maven2/io/apicurio/apicurio-maven-plugin/1.3.5.Final/apicurio-maven-plugin-1.3.5.Final.jar
# jackson
RUN curl -O https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar
RUN curl -O https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-core/2.14.2/jackson-core-2.14.2.jar
RUN curl -O https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.14.2/jackson-annotations-2.14.2.jar
RUN curl -O https://repo.maven.apache.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.14.2/jackson-dataformat-csv-2.14.2.jar
# log redactor
RUN curl -O https://repo.maven.apache.org/maven2/io/confluent/logredactor/1.0.12/logredactor-1.0.12.jar
RUN curl -O https://repo.maven.apache.org/maven2/io/confluent/logredactor-metrics/1.0.12/logredactor-metrics-1.0.12.jar


RUN ls -ls
WORKDIR /kafka